"""add user preferences model

Revision ID: 05f202836a5b
Revises: 8c96f0a11496
Create Date: 2024-12-29 23:59:47.780362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f202836a5b'
down_revision: Union[str, None] = '68664dd8a6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ZH', name='language'), nullable=False),
    sa.Column('currency', sa.Enum('CAD', 'USD', 'CNY', name='currency'), nullable=False),
    sa.Column('theme', sa.Enum('FRESH', 'NATURAL', 'OCEAN', 'SUNSET', name='theme'), nullable=False),
    sa.Column('login_expire_days', sa.Integer(), nullable=False),
    sa.Column('require_password_on_launch', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user_settings', sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False, comment='是否启用两步验证'))
    op.add_column('user_settings', sa.Column('security_question_set', sa.Boolean(), nullable=False, comment='是否设置了安全问题'))
    op.add_column('user_settings', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, comment='是否启用邮件通知'))
    op.add_column('user_settings', sa.Column('account_locked', sa.Boolean(), nullable=False, comment='账户是否被锁定'))
    op.add_column('user_settings', sa.Column('last_password_reset_at', sa.DateTime(), nullable=True, comment='上次密码重置时间'))
    op.drop_column('user_settings', 'notification_enabled')
    op.drop_column('user_settings', 'require_password_on_launch')
    op.drop_column('user_settings', 'language')
    op.drop_column('user_settings', 'login_expire_days')
    op.drop_column('user_settings', 'currency')
    op.drop_column('user_settings', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('theme', sa.VARCHAR(length=7), nullable=False))
    op.add_column('user_settings', sa.Column('currency', sa.VARCHAR(length=3), nullable=False))
    op.add_column('user_settings', sa.Column('login_expire_days', sa.INTEGER(), nullable=False))
    op.add_column('user_settings', sa.Column('language', sa.VARCHAR(length=2), nullable=False))
    op.add_column('user_settings', sa.Column('require_password_on_launch', sa.BOOLEAN(), nullable=False))
    op.add_column('user_settings', sa.Column('notification_enabled', sa.BOOLEAN(), nullable=False))
    op.drop_column('user_settings', 'last_password_reset_at')
    op.drop_column('user_settings', 'account_locked')
    op.drop_column('user_settings', 'email_notifications_enabled')
    op.drop_column('user_settings', 'security_question_set')
    op.drop_column('user_settings', 'is_two_factor_enabled')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
