"""Initial migration

Revision ID: 68664dd8a6ab
Revises: 
Create Date: 2024-12-24 23:07:10.182959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68664dd8a6ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('module_key', sa.String(length=255), nullable=False, comment='feature module key'),
    sa.Column('config_schema', sa.JSON(), nullable=True, comment='feature config schema'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_feature_key'), 'features', ['feature_key'], unique=True)
    op.create_table('menu_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=255), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('custom_order', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FEATURE', 'SETTING', name='menutype'), nullable=False, comment='menu type: feature menu or setting menu'),
    sa.Column('group', sa.Enum('MAIN', 'SYSTEM', name='menugroup'), nullable=False, comment='menu group: main function area or system area'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='menu display name'),
    sa.Column('icon', sa.String(length=255), nullable=False, comment='menu icon identifier'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='parent menu id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_configs_menu_key'), 'menu_configs', ['menu_key'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_permission_key'), 'permissions', ['permission_key'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='accountstatus'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('feature_permissions',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'permission_id', 'id')
    )
    op.create_table('menu_required_features',
    sa.Column('menu_config_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['menu_config_id'], ['menu_configs.id'], ),
    sa.PrimaryKeyConstraint('menu_config_id', 'feature_id', 'id')
    )
    op.create_table('user_session',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True, comment='操作系统信息'),
    sa.Column('model', sa.String(length=255), nullable=True, comment='设备型号信息'),
    sa.Column('manufacturer', sa.String(length=255), nullable=True, comment='设备制造商'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='最后已知IP地址'),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_token'), 'user_session', ['token'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ZH', name='language'), nullable=False),
    sa.Column('currency', sa.Enum('CAD', 'USD', name='currency'), nullable=False),
    sa.Column('theme', sa.Enum('FRESH', 'NATURAL', 'OCEAN', 'SUNSET', name='theme'), nullable=False),
    sa.Column('login_expire_days', sa.Integer(), nullable=False),
    sa.Column('require_password_on_launch', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_session_token'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_table('menu_required_features')
    op.drop_table('feature_permissions')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_permissions_permission_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_menu_configs_menu_key'), table_name='menu_configs')
    op.drop_table('menu_configs')
    op.drop_index(op.f('ix_features_feature_key'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
