"""Initial migration4

Revision ID: 86d3ea6eb6e3
Revises: 9ee5e8dcf2db
Create Date: 2024-12-16 16:54:41.664783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d3ea6eb6e3'
down_revision: Union[str, None] = '9ee5e8dcf2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_feature_key'), 'features', ['feature_key'], unique=True)
    op.create_table('menu_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=255), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('custom_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_configs_menu_key'), 'menu_configs', ['menu_key'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_permission_key'), 'permissions', ['permission_key'], unique=True)
    op.create_table('feature_permissions',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'permission_id', 'id')
    )
    op.create_table('menu_required_features',
    sa.Column('menu_config_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['menu_config_id'], ['menu_configs.id'], ),
    sa.PrimaryKeyConstraint('menu_config_id', 'feature_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_required_features')
    op.drop_table('feature_permissions')
    op.drop_index(op.f('ix_permissions_permission_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_menu_configs_menu_key'), table_name='menu_configs')
    op.drop_table('menu_configs')
    op.drop_index(op.f('ix_features_feature_key'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
