"""Initial migration3

Revision ID: 9ee5e8dcf2db
Revises: 4ef9047d5d10
Create Date: 2024-12-16 16:52:20.877430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee5e8dcf2db'
down_revision: Union[str, None] = '4ef9047d5d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
